version: '3.8'

services:
  # Vector database for embeddings
  qdrant:
    image: qdrant/qdrant:latest
    container_name: freibot-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped

  # Python app for LangChain RAG processing
  freibot-api:
    build: .
    container_name: freibot-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_data:
