version: '3.8'

services:
  # Python app for LangChain RAG processing
  freibot-api:
    build: .
    container_name: freibot-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    env_file:
    - ./.env
    restart: unless-stopped
